version: "3.8"

services:
  premd:
    container_name: premd
    image: ghcr.io/premai-io/premd:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    environment:
      - PREM_REGISTRY_URL=${PREM_REGISTRY_URL}
      - SENTRY_DSN=${SENTRY_DSN}

  prem_app:
    image: ghcr.io/premai-io/prem-app:latest
    ports:
      - 5173:5173
    environment:
      - VITE_ENABLE_STREAMING=0
      - VITE_DESTINATION=browser
      - VITE_IS_PACKAGED=true
