version: "3"

services:
  premd:
    container_name: premd
    image: ghcr.io/premai-io/premd:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    env_file:
      - .env

  # prem_app:
  #   image: ghcr.io/premai-io/prem-app:latest
  #   env_file:
  #     - .env
  #   ports:
  #     - 5173:5173
